# Generated by Django 2.1.4 on 2019-01-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuhackit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser',
            name='max_inventory',
            field=models.IntegerField(default='10'),
        ),
    ]
